# Generated by Django 4.2.7 on 2023-12-03 20:54

from django.db import migrations, models
import django.db.models.deletion
import generateContract.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=255)),
                ('contract_description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(validators=[generateContract.models.validate_endate])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('signing_bonus', models.IntegerField()),
                ('equipment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateContract.contract')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateContract.game')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateContract.gamer'),
        ),
    ]
